#!/bin/bash

options=(
  style=round
  width=6.0
  hidpi=off
  active_color="gradient(top_left=0xff8839ef,bottom_right=0xffb4befe)"
  inactive_color="gradient(top_right=0xffe2e2e2, bottom_left=0xffcfcfcf)"
)

borders "${options[@]}"
