services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    env_file: .env
    security_opt:
      - no-new-privileges:true
    mem_limit: 2g
    cpu_shares: 768
    environment:
      - TZ=Europe/Paris
    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
    networks:
      proxy_net:
      vlan60_services:
        ipv4_address: ${AD_GUARD_IP}

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguard.rule=Host(`adguard.${DOMAIN}`)"
      - "traefik.http.routers.adguard.entrypoints=https"
      - "traefik.http.routers.adguard.tls=true"
      - "traefik.http.routers.adguard.tls.certresolver=cloudflare"
      - "traefik.http.services.adguard.loadbalancer.server.port=80"

networks:
  proxy_net:
    external: true
  vlan60_services:
    name: vlan60_services
    driver: macvlan
    driver_opts:
      parent: ${PARENT_LAN}
    ipam:
      config:
        - subnet: ${SUBNET}
          gateway: ${GATEWAY}
