services:
  bichon:
    image: rustmailer/bichon:latest
    container_name: bichon
    restart: unless-stopped
    ports:
      - 3006:15630
    volumes:
      - ./data:/data
      - /mnt/nas-bichon/eml:/data/eml
    environment:
      BICHON_ROOT_DIR: /data
      BICHON_LOG_LEVEL: info

networks:
  proxy_net:
    external: true

