services:
  uptime-kuma:
    container_name: uptime_kuma
    image: louislam/uptime-kuma:2
    restart: unless-stopped
    environment:
      - PORT=8034
    networks:
      - proxy_net
    volumes:
      - ./data:/app/data
    extra_hosts:
      - "${DASHBOARD}:host-gateway"
      - "${ADGUARD}:host-gateway"
      - "${INFRA}:host-gateway"
      - "${MONITOR}:host-gateway"
      - "${DOCKER}:host-gateway"
      - "${DOCKER2}:host-gateway"
      - "${NOTIF}:host-gateway"
      - "${BACKUPS}:host-gateway"
      - "${LOGS}:host-gateway"
      - "${WEBMAIL}:host-gateway"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kuma.rule=Host(`status.${DOMAIN}`)"
      - "traefik.http.routers.kuma.entrypoints=https"
      - "traefik.http.routers.kuma.tls=true"
      - "traefik.http.routers.kuma.tls.certresolver=cloudflare"
      - "traefik.http.routers.kuma.middlewares=crowdsec-bouncer@docker"
      - "traefik.http.services.kuma.loadbalancer.server.port=8034"

networks:
  proxy_net:
    external: true
