services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    env_file: .env
    # deploy:
    #   resources:
    #     limits:
    #       memory: 512M
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"

    networks:
      proxy_net:
      vlan60_services:
        ipv4_address: ${MAILSERVER_IP}
    volumes:
      - ./mail:/var/mail
      - ./config/:/tmp/docker-mailserver/
      - ./logs/:/var/log/mail/

      - ./state/indices:/var/mail-state/indices
      - ./state/control:/var/mail-state/control

      - /etc/localtime:/etc/localtime:ro
      - ${SSL_CERT_PATH_LOCAL}:/tmp/ssl/fullchain.pem:ro
      - ${SSL_KEY_PATH_LOCAL}:/tmp/ssl/privkey.pem:ro
    restart: always
    environment:
      - DMS_VMAIL_UID=${MY_UID}
      - DMS_VMAIL_GID=${MY_GID}
      - DOVECOT_USER_ATTRS==home=/var/mail/%d/%n,=uid=${MY_UID},=gid=${MY_GID}
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/tmp/ssl/fullchain.pem
      - SSL_KEY_PATH=/tmp/ssl/privkey.pem
      # disable to be able to get/read old mail
      - ENABLE_AMAVIS=0
      - ENABLE_SPAMASSASSIN=0
      - TZ=${TZ}

networks:
  vlan60_services:
    external: true
  proxy_net:
    external: true

