services:
  immich_machine_learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://docs.immich.app/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    ports:
      - "3066:3003"
    env_file:
      - .env
    restart: always
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "2.0" # Permet d'utiliser 2 cœurs pour l'IA
    #       memory: 1024M # Limite stricte à 2 Go
    #     reservations:
    #       memory: 256M # Réserve 512 Mo au démarrage
    healthcheck:
      disable: false

volumes:
  model-cache:
