services:
  paperless_gpt:
    container_name: paperless_gpt
    image: icereed/paperless-gpt:latest
    env_file: .env
    environment:
      PAPERLESS_BASE_URL: ${PAPERLESS_BASE_URL}
      PAPERLESS_API_TOKEN: ${PAPERLESS_API_TOKEN}
      PAPERLESS_PUBLIC_URL: ${PAPERLESS_PUBLIC_URL}
      MANUAL_TAG: ${MANUAL_TAG}
      AUTO_TAG: ${AUTO_TAG}
      LLM_PROVIDER: ${LLM_PROVIDER}
      LLM_MODEL: ${LLM_MODEL}
      LLM_LANGUAGE: ${LLM_LANGUAGE}
      OCR_PROVIDER: ${OCR_PROVIDER}
      VISION_LLM_PROVIDER: ${VISION_LLM_PROVIDER}
      VISION_LLM_MODEL: ${VISION_LLM_MODEL}
      OLLAMA_HOST: ${OLLAMA_HOST}
      OCR_PROCESS_MODE: ${OCR_PROCESS_MODE}
      PDF_SKIP_EXISTING_OCR: ${PDF_SKIP_EXISTING_OCR}
      CREATE_LOCAL_HOCR: ${CREATE_LOCAL_HOCR}
      AUTO_OCR_TAG: ${AUTO_OCR_TAG}
      OCR_LIMIT_PAGES: ${OCR_LIMIT_PAGES}
      LOG_LEVEL: ${LOG_LEVEL}
    volumes:
      - ./prompts:/app/prompts
      - ./hocr:/app/hocr
      - ./pdf:/app/pdf
    networks:
      - proxy_net
      - paperless_net
    extra_hosts:
      - "paperless.armanoide.net:host-gateway"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paperless-gpt.rule=Host(`gpt.paperless.${DOMAIN}`)"
      - "traefik.http.routers.paperless-gpt.entrypoints=https"
      - "traefik.http.routers.paperless-gpt.tls=true"
      - "traefik.http.routers.paperless-gpt.tls.certresolver=cloudflare"
      - "traefik.http.services.paperless-gpt.loadbalancer.server.port=8080"
networks:
  proxy_net:
    external: true
  paperless_net:
    external: true
