services:
  garage:
    container_name: garage
    image: dxflrs/garage:v2.2.0
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - RUST_LOG=garage=info
    ports:
      - "3903:3903"
      - "3900:3900"
    volumes:
      - ./garage.toml:/etc/garage.toml
      - ./meta:/var/lib/garage/meta
      - ${DATA_PATH}:/var/lib/garage/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.garage_s3.rule=Host(`s3.${DOMAIN}`)"
      - "traefik.http.routers.garage_s3.entrypoints=https"
      - "traefik.http.routers.garage_s3.tls=true"
      - "traefik.http.routers.garage_s3.tls.certresolver=cloudflare"
      - "traefik.http.services.garage_s3.loadbalancer.server.port=3900"

    networks:
      - proxy_net

networks:
  proxy_net:
    external: true

