services:
  nvim_editor:
    container_name: nvim_editor
    build:
      context: .
      args:
        CONTAINER_UID: ${CONTAINER_UID}
        CONTAINER_GID: ${CONTAINER_GID}
    volumes:
      - /:/internal_volume:rw
      # nvim config for root (--root mode)
      - ${NVIM_CONFIG_HOST}:/root/.config/nvim
      # nvim config for nvim user (default mode)
      - ${NVIM_CONFIG_HOST}:/home/nvim/.config/nvim
    privileged: true
    stdin_open: true
    tty: true
    network_mode: host
