services:
  nextcloud_db:
    image: mariadb:lts
    container_name: nextcloud_db
    restart: always
    networks:
      - mail_network
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - nextcloud_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}

  nextcloud_redis:
    image: redis:alpine
    restart: always
    container_name: nextcloud_redis
    volumes:
      - nextcloud_redis:/data
    networks:
      - mail_network

  nextcloud_app:
    image: nextcloud
    container_name: nextcloud_app
    restart: always
    ports:
      - 8818:80
    networks:
      - mail_network
    depends_on:
      - nextcloud_redis
      - nextcloud_db
    volumes:
      - ./html:/var/www/html
      - /volume1/NextCloud:/var/www/html/data
      - ./nextcloud.log:/var/www/html/data/nextcloud.log
      - ./${APP_FOLDER}:/var/www/html/data/${APP_FOLDER}

    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=nextcloud_db
      - REDIS_HOST=nextcloud_redis
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}

volumes:
  nextcloud:
  nextcloud_db:
  nextcloud_redis:
    name: nextcloud_redis

networks:
  mail_network:
    external: true
